name: "Terraform Deploy Storage on GCP"

on:
  workflow_dispatch:  # REQUIRED for API calls

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        #run: |
          #echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > gcp-key.json
          #gcloud auth activate-service-account --key-file=gcp-key.json
          #gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./modules/Google/storage

      - name: Validate Terraform Configuration  
        run: terraform validate
        working-directory: ./modules/Google/storage

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: ./modules/Google/storage

      - name: Terraform Plan
        run: terraform plan -var="project_id=${{ secrets.GCP_PROJECT_ID }}"
        working-directory: ./modules/Google/storage
# Need to uncomment the code hier in order to deploy the resources 
      - name: Terraform Apply
        run:  terraform apply -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID }}"
        working-directory: ./modules/Google/storage

      - name: Get Output (Bucket URL)
        run: terraform output bucket_url
        working-directory: ./modules/Google/storage
